const id=__ID__,root=document.getElementById(id);if(!root||root.dataset.ready)return;
root.dataset.ready='true';const panel=root.querySelector('.m3-sheet__surface'),scrim=root.querySelector('.m3-sheet__scrim'),handle=root.querySelector('[data-sheet-handle]');
const modal=root.dataset.modal==='true',reduced=matchMedia('(prefers-reduced-motion:reduce)');
let animations=[],epoch=0,opener,overflow,locked=false,active=false,drag,suppressClick=false;
const controls=()=>[...root.querySelectorAll('button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex="0"]')].filter(e=>e.getClientRects().length);
const unlock=()=>{if(locked){document.documentElement.style.overflow=overflow;locked=false;}if(opener?.isConnected&&(modal||root.contains(document.activeElement)))opener.focus({preventScroll:true});};
const settings=()=>{const style=getComputedStyle(root);return {ms:name=>{if(reduced.matches)return 0;const value=style.getPropertyValue(`--m3-${name}-duration`).trim(),number=parseFloat(value);return Number.isFinite(number)?number*(value.endsWith('ms')?1:1000):(name==='default-spatial'?440:240);},ease:name=>style.getPropertyValue(`--m3-${name}`).trim()||'cubic-bezier(.2,0,0,1)',spatial:style.getPropertyValue('--m3-sheet-spatial').trim()||style.getPropertyValue('--m3-default-spatial').trim()};};
const off=()=>{const side=root.dataset.side,rtl=getComputedStyle(root).direction==='rtl';return side==='bottom'?'translateY(100%)':side==='top'?'translateY(-100%)':`translateX(${(side==='start')!==rtl?'-':''}100%)`;};
const sync=()=>{
 const open=root.dataset.open==='true',token=++epoch,from=active?getComputedStyle(panel).transform:null,shade=scrim&&active?getComputedStyle(scrim).opacity:'0',shadow=active?getComputedStyle(panel).boxShadow:null;
 animations.forEach(a=>a.cancel());
 const restingShadow=getComputedStyle(panel).boxShadow,clear='0 1px 3px 0 rgb(0 0 0 / 0),0 1px 2px 0 rgb(0 0 0 / 0)';
 if(open&&!active){opener=document.activeElement;active=true;if(modal){overflow=document.documentElement.style.overflow;document.documentElement.style.overflow='hidden';locked=true;root.showModal();}controls()[0]?.focus({preventScroll:true});}
 if(!active)return;
 if(open&&!modal&&!root.getClientRects().length){root.dataset.phase='open';return;}
 const s=settings();root.dataset.phase=open?'opening':'closing';
 panel.style.transform='';if(scrim)scrim.style.opacity='';
 animations=[panel.animate([{transform:from!==null?(from==='none'?'translate(0)':from):(open?off():'translate(0)')},{transform:open?'translate(0)':off()}],{duration:s.ms('default-spatial'),easing:s.spatial,fill:'both'})];
 if(modal){animations.push(panel.animate([{boxShadow:shadow||clear},{boxShadow:open?restingShadow:clear}],{duration:s.ms('default-effects'),easing:s.ease('default-effects'),fill:'both'}));if(scrim)animations.push(scrim.animate([{opacity:shade},{opacity:open?1:0}],{duration:s.ms('default-effects'),easing:s.ease('default-effects'),fill:'both'}));}
 Promise.all(animations.map(a=>a.finished)).then(()=>{if(token!==epoch)return;root.dataset.phase=open?'open':'closed';if(!open){active=false;if(modal)root.close();unlock();}animations.forEach(a=>a.cancel());}).catch(()=>{});
};
const request=action=>dioxus.send(action);
const cancel=e=>{e.preventDefault();request('close');};
const click=e=>{if(suppressClick&&handle?.contains(e.target)){e.preventDefault();e.stopImmediatePropagation();suppressClick=false;return;}if(e.target===scrim)request('close');};
const key=e=>{if(e.target===handle&&(e.key==='Enter'||e.key===' '))suppressClick=false;if(e.key==='Escape'&&!modal&&root.dataset.open==='true'){e.preventDefault();request('close');}if(e.target===handle&&(e.key==='ArrowUp'||e.key==='ArrowDown')){e.preventDefault();request(e.key==='ArrowUp'?'expand':'collapse');}if(!modal||e.key!=='Tab')return;const items=controls(),first=items[0],last=items.at(-1);if(!first)return;if(e.shiftKey&&(document.activeElement===first||!root.contains(document.activeElement))){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||!root.contains(document.activeElement))){e.preventDefault();first.focus();}};
const down=e=>{if(root.dataset.draggable!=='true'||e.button!==0||root.dataset.open!=='true')return;const transform=getComputedStyle(panel).transform;const y=transform==='none'?0:new DOMMatrixReadOnly(transform).m42;epoch++;animations.forEach(a=>a.cancel());drag={id:e.pointerId,y:e.clientY,offset:y,delta:0,height:panel.getBoundingClientRect().height,expanded:root.dataset.expanded==='true'};panel.style.transition='none';suppressClick=false;handle.setPointerCapture(e.pointerId);};
const move=e=>{if(!drag||e.pointerId!==drag.id)return;drag.delta=e.clientY-drag.y;if(Math.abs(drag.delta)>8)suppressClick=true;if(drag.delta<0||drag.expanded){const available=modal?innerHeight:root.getBoundingClientRect().height,margin=modal?(innerWidth>640?56:72):16;panel.style.height=Math.max(available*.5,Math.min(available-margin,drag.height-drag.delta))+'px';}else if(drag.delta>0){panel.style.transform=`translateY(${Math.max(0,drag.offset+drag.delta)}px)`;if(scrim)scrim.style.opacity=Math.max(0,1-drag.delta/panel.getBoundingClientRect().height);}e.preventDefault();};
const end=e=>{if(!drag||e.pointerId!==drag.id)return;const delta=drag.delta,threshold=Math.min(96,drag.height*.2);panel.getBoundingClientRect();panel.style.transition='';panel.style.height='';drag=null;if(e.type==='pointercancel'){suppressClick=true;sync();return;}if(delta < -threshold){request('expand');sync();}else if(delta>threshold){if(root.dataset.expanded==='true'){request('collapse');sync();}else {request('close');sync();}}else sync();};
const motion=()=>{if(reduced.matches)animations.forEach(a=>a.finish());};
const observer=new MutationObserver(records=>{if(records.some(r=>r.attributeName==='data-open'))sync();});observer.observe(root,{attributes:true,attributeFilter:['data-open']});
root.addEventListener('cancel',cancel);root.addEventListener('click',click,true);root.addEventListener('keydown',key);reduced.addEventListener('change',motion);
handle?.addEventListener('pointerdown',down);handle?.addEventListener('pointermove',move);handle?.addEventListener('pointerup',end);handle?.addEventListener('pointercancel',end);sync();
window.__m3Sheets??={};window.__m3Sheets[id]=()=>{++epoch;animations.forEach(a=>a.cancel());observer.disconnect();root.removeEventListener('cancel',cancel);root.removeEventListener('click',click,true);root.removeEventListener('keydown',key);reduced.removeEventListener('change',motion);handle?.removeEventListener('pointerdown',down);handle?.removeEventListener('pointermove',move);handle?.removeEventListener('pointerup',end);handle?.removeEventListener('pointercancel',end);if(modal&&root.open)root.close();unlock();delete window.__m3Sheets[id];};
