#!/usr/bin/env node
// Generates src/icons.rs from the official Material Symbols SVG package.
//
//   npm i @material-symbols/svg-400@0.48.0   (Apache-2.0, Google)
//   node scripts/gen-icons.mjs node_modules/@material-symbols/svg-400/rounded
//
// Only the names listed below are written, so the bundle stays small. Add a
// name here, rerun the script, and commit the regenerated file.
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const src = process.argv[2];
if (!src) {
  console.error("usage: node scripts/gen-icons.mjs <path to @material-symbols/svg-400/rounded>");
  process.exit(1);
}

// [rust const name, official file stem]. A stem ending in "-fill" is the filled glyph.
const ICONS = [
  ["ADD", "add"],
  ["ARROW_BACK", "arrow_back"],
  ["ARROW_DROP_DOWN", "arrow_drop_down"],
  ["CANCEL", "cancel"],
  ["CHECK", "check"],
  ["CHECK_CIRCLE", "check_circle"],
  ["CHEVRON_LEFT", "chevron_left"],
  ["CHEVRON_RIGHT", "chevron_right"],
  ["CLOSE", "close"],
  ["FAVORITE", "favorite"],
  ["FAVORITE_FILL", "favorite-fill"],
  ["INFO", "info"],
  ["KEYBOARD_ARROW_DOWN", "keyboard_arrow_down"],
  ["REMOVE", "remove"],
];

const version = JSON.parse(readFileSync(join(src, "../package.json"), "utf8")).version;
const out = [];
out.push("// Generated by scripts/gen-icons.mjs. Do not edit by hand.");
out.push(`// Material Symbols Rounded from @material-symbols/svg-400@${version} (Apache-2.0, Google).`);
out.push("// Paths use the 960-unit grid; viewBox is \"0 -960 960 960\".");
out.push("");
out.push("use crate::components::IconData;");
out.push("");
for (const [constName, stem] of ICONS) {
  const svg = readFileSync(join(src, `${stem}.svg`), "utf8");
  const d = svg.match(/ d="([^"]+)"/);
  if (!d) throw new Error(`no path in ${stem}.svg`);
  out.push(`pub const ${constName}: IconData = IconData {`);
  out.push(`    name: "${stem}",`);
  out.push(`    path: "${d[1]}",`);
  out.push("};");
}
const target = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "icons.rs");
writeFileSync(target, out.join("\n") + "\n");
console.log(`wrote ${ICONS.length} icons to ${target}`);
